### ISSUE TITLE
LoginPage_Java

### ISSUE THREAD

**Issue by thuctapnhom02** [thuctapnhom02/MockProject_102024_Nhom02#13]
Interface of Login Page with Java code

**Comment by ambrouse** [comment]
https://drive.google.com/drive/folders/1DX8zCDSulG_CPLwZl9vhDoPiiT4EaFfE?usp=sharing
![loginpage](https://github.com/user-attachments/assets/7a774b1e-dcd8-4df5-aa34-af6934e76acc)

**Comment by ambrouse** [comment]
https://drive.google.com/drive/folders/1DX8zCDSulG_CPLwZl9vhDoPiiT4EaFfE?usp=drive_link
![loginpage](https://github.com/user-attachments/assets/e4c674f3-239a-4ff8-b911-160765ca5b73)

**Comment by tramttb** [comment]
https://drive.google.com/drive/folders/1si3qtDoscDw6rdh9EePbJbjlKeTNr1GW?usp=drive_link
