### ISSUE TITLE
LoginPage_Python

### ISSUE THREAD

**Issue by thuctapnhom02** [thuctapnhom02/MockProject_102024_Nhom02#14]
Interface of LoginPage with Python

**Comment by thuctapnhom02** [comment]
https://drive.google.com/drive/folders/1qMMYPLEuQ-DBKZG7GvFj_6alaS9quulU?usp=sharing
![webchungcu](https://github.com/user-attachments/assets/083f5899-3aa5-4273-a389-e2b12d3b73c0)

**Comment by Miku2906** [comment]
https://drive.google.com/drive/folders/1qMMYPLEuQ-DBKZG7GvFj_6alaS9quulU?usp=drive_link

![webchungcu](https://github.com/user-attachments/assets/5ee54402-df99-4dde-b044-4c05091f0326)
