### ISSUE TITLE
Tester: FigmaDesign

### ISSUE THREAD

**Issue by thuctapnhom02** [thuctapnhom02/MockProject_102024_Nhom02#27]
Design a figma of the payment page

**Comment by NgoTanKhoa21042001** [comment]
![image](https://github.com/user-attachments/assets/586daf34-8b15-4f34-b474-f35f603db2d3)

**Comment by NgoTanKhoa2104-star** [comment]
![image](https://github.com/user-attachments/assets/7544b021-3ce1-4a11-a94b-92e0747a10bc)
