### ISSUE TITLE
Interface: Header + Footer

### ISSUE THREAD

**Issue by thuctapnhom02** [thuctapnhom02/MockProject_102024_Nhom02#37]

**Comment by Duyan04** [comment]
https://github.com/Duyan04/duanthutap.git

**Comment by Tuananh458** [comment]
https://github.com/Tuananh458/UI_staff.git

**Comment by Duyan04** [comment]
https://github.com/Duyan04/duanthutap.git

**Comment by 7x763** [comment]
https://github.com/7x763/UI_STAFF.git
